export const homecards = [
  {
    id: 1,
    images: ['https://picsum.photos/700', 'https://picsum.photos/700'],
    event: 'world cancer day',
    hospitalName: 'Mulago Hospital',
    displayPicture: 'https://picsum.photos/700',
    time: '2 hours ago',
    likes: 10,
    comments: [],
  },
  {
    id: 2,
    images: ['https://picsum.photos/700'],
    event: 'charity',
    hospitalName: 'Kawempe Hospital',
    displayPicture: 'https://picsum.photos/700',
    time: '2 hours aga',
    likes: 10,
    comments: ['clear'],
  },
  {
    id: 3,
    images: [
      'https://picsum.photos/700',
      'https://picsum.photos/700',
      'https://picsum.photos/700',
    ],
    event: 'immunisation',
    hospitalName: 'Mulago Hospital',
    displayPicture: 'https://picsum.photos/700',
    time: '5 minutes ago',
    likes: 10,
    comments: ['clear', 'we love this', 'so funny'],
  },
  {
    id: 4,
    images: [
      'https://picsum.photos/700',
      'https://picsum.photos/700',
      'https://picsum.photos/700',
      'https://picsum.photos/700',
      'https://picsum.photos/700',
    ],
    event: 'immunisation',
    hospitalName: 'Gayaza Hospital',
    displayPicture: 'https://picsum.photos/700',
    time: '1 hours ago',
    likes: 10,
    comments: ['good hearted', 'so good', 'we are set'],
  },
];
